In [1]:
import numpy as np 

In [2]:
import math

In [3]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

mean absolute error 

In [4]:
def mean_absolute_error(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yp-yt)
        # abs will give us absolute difference 

    print("total error ",total_error)
    mae=total_error/len(y_true)
    print("mean_absolute_error",mae)

In [5]:
mean_absolute_error(y_true,y_predicted)

total error  2.5
mean_absolute_error 0.5


In [6]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [7]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [8]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [9]:
np.mean(np.abs(y_predicted-y_true))

0.5

mean squared error 

In [10]:
def mean_squared_error(y_true,y_predicted):
    total_error=0
    for tv,pv in zip(y_true,y_predicted):
        total_error += pow(abs(tv-pv),2)
    print("total error ",total_error)
    msq=total_error/len(y_true)
    print(msq)

In [11]:
mean_squared_error(y_true,y_predicted)

total error  1.83
0.366


knowing important thing about log 

In [12]:
np.log(0)

C:\Users\hp\AppData\Local\Temp\ipykernel_7228\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [13]:
np.log([0.000000000000001])

array([-34.53877639])

so we come to know that log zero is infinte so it is not defiend on that 

log loss or binary cross entrophy =1/n(Eyi log(y predicted)+(1-yi).log(1-ypredicted))

we cannot take y predicted and true as 1 because it will let you go to the log 0 whic is termed to infintie 

In [14]:
eplison=1e-15

In [15]:
eplison

1e-15

In [16]:
y_predicted

array([1, 1, 0, 0, 1])

In [17]:
y_predicted_new =[max(i,eplison) for i in y_predicted]

In [18]:
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [19]:
y_predicted_new=(min(i,1-eplison) for i in y_predicted_new)

In [20]:
y_predicted_new

<generator object <genexpr> at 0x000002130C6E2F20>

In [21]:
for i in y_predicted_new:
    print(i)

0.999999999999999
0.999999999999999
1e-15
1e-15
0.999999999999999


In [23]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

TypeError: loop of ufunc does not support argument 0 of type generator which has no callable log method