In [1]:
import numpy as np 

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

creating the two numpy array which can be termed as a matrix first one is revenue and the second one is expenses 

In [4]:
revenue.ndim

2

In [5]:
profit=revenue-expenses

In [6]:
profit


array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [7]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

for dot product we have a function in numpy 

In [8]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

here it is not a dot product it is a simple multiplication done by the numpy array here it is expanded the price per unit into the two d array as our as requirement for more we can go to the documentation of this 

for dot product we have a function np.dot by using this function we can do the dot product of the array

In [9]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])